site_name: Dmitry Tsybus / Docs
site_url: https://docs.ditsi.ru
plugins:
  - search:
  - exclude:
      glob:
        - "ansible/*"

extra:
  analytics:
    provider: google
    property: G-VKYGDZ78CK

theme:
  name: material
  features:
    - search-suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tabs
    - header.autohide